import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/Navbar";
import Banner from "@/components/Banner";
import { EventProvider } from "@/context/eventContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <EventProvider>
      <body className={inter.className}>
        <Navbar />
        <Banner />
        {children}
      </body>
      </EventProvider>
    </html>
  );
}
